{
  perform: true,
  commands: [
    {
      type: 'label',
      name: 'Needs Logs',
      allowTriggerByBot: false,
      action: 'comment',
      comment: 'Looks like we need for info to debug your particular issue. If you could attach your logs (ensure no private data is in them) to the issue it would help us fix the issue much faster.\n\nTo find your logs run the command `Developer: Open Logs Folder`, this will open the log file locally. We generally care most about renderer.log'
    }
  ]
}
